// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrpaljickycxntfgwjgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpycGFsamlja3ljeG50Zmd3amdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTQxMzksImV4cCI6MjA2MTU3MDEzOX0.JhBekHoXXWJWhLbptV-vEl8HxBx_ohT-LD2kI2-oSFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);